kiosk-shell: include config.h
Every .c file must include config.h as the first thing.

Without this, when a later patch tries to use xstrdup() here, the build
will:

In file included from ../../git/weston/kiosk-shell/kiosk-shell.c:37:
../../git/weston/shared/xalloc.h: In function ‘abort_oom_if_null’:
../../git/weston/shared/xalloc.h:48:40: error: ‘program_invocation_short_name’ undeclared (first use in this function)
   48 |         written = write(STDERR_FILENO, program_invocation_short_name,
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../git/weston/shared/xalloc.h:48:40: note: each undeclared identifier is reported only once for each function it appears in

This is caused by the lack of _GNU_SOURCE.

Signed-off-by: Pekka Paalanen <pekka.paalanen@collabora.com>