backend-drm: fix maybe uninitialized num_planes
In function ‘drm_fb_maybe_import’,
    inlined from ‘drm_fb_addfb’ at ../../git/weston/libweston/backend-drm/fb.c:236:8:
../../git/weston/libweston/backend-drm/fb.c:210:31: error: ‘num_planes’ may be used uninitialized [-Werror=maybe-uninitialized]
  210 |         for (plane = 0; plane < num_planes; plane++) {

Direct-display is mutually exclusive with having GBM BO, because the
point of direct-display is to not import to GBM. We can use this to make
the logic more provable to the compiler, and be more obvious about the
expectation to the human reader.

Signed-off-by: Pekka Paalanen <pekka.paalanen@collabora.com>